### ISSUE TITLE
Support Django 4

### ISSUE THREAD

**Issue by PeterJCLaw** [danpalmer/django-devdata#11]
Discovered while adding CI versions for #9.
Currently the tests fail with: `django.db.utils.ProgrammingError: relation "django_migrations" does not exist` during `export_migration_state`.
I don't know if that's just a test setup issue or a genuine change in Django 4. A quick look at the release notes didn't reveal anything obvious unfortunately.

**Comment by aaron7-mns** [comment]
It's a change in Django: https://github.com/django/django/pull/15252 where we were relying on `django_migrations` being created even when there are no migrations to run.

**Comment by PeterJCLaw** [comment]
Looks like we can just call `MigrationRecorder(connection).ensure_schema()` to have Django create the table? Not sure if that's meant to be public API or not, but seems like it would get things working.

**Comment by PeterJCLaw** [comment]
Hrm, adding `MigrationRecorder(connection).ensure_schema()` to the top of the _export_ tests makes them pass. However I had thought that when this issue was seen under Django 4 it was seen at _import_ time? :confused:

**Comment by PeterJCLaw** [comment]
Ah, I think this only occurs at import time if there are any migration records to restore. If not then it looks like the access to `django_migrations` is skipped (by dint of using `executemany` on an empty list). That would explain why the tests aren't impacted (since they have no migration records).
