### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lorenzomorandini** [danpalmer/django-devdata#39]
Is there a plan for a new release? The README talk about a few things (like the --reset-mode param of the import command) that aren't in the 1.0.0 release.

**Comment by PeterJCLaw** [comment]
@danpalmer do you think we could progress #37 and then perhaps do a release?

**Comment by danpalmer** [comment]
@lorenzomorandini apologies, I've just approved #37 and will cut a release now

**Comment by danpalmer** [comment]
Done! https://pypi.org/project/django-devdata/
