### ISSUE TITLE
Drop legacy Python support

### ISSUE THREAD

**Issue by PeterJCLaw** [danpalmer/django-devdata#6]
Can we drop support for Python < 3.6? I'd even be tempted to drop < 3.7 to be honest.

I also noticed that this project doesn't declare a dependency on Django(!), however when adding one `poetry` wants to update the Python requirement to at least 3.6.

**Comment by danpalmer** [comment]
Yes, feel free to go to 3.7. I can't remember the right way to express the dependency on Django, but we don't want to constrain Django versions any more than necessary. I'd rather be too open and it not work on newer versions, than too strict and it need updating every release, but up to you.
